[versions]
agp = "8.5.1"
kotlin = "2.2.10"
coroutines = "1.10.1"
android-compileSdk = "34"
android-minSdk = "26"
android-targetSdk = "34"
ksp = "2.2.10-2.0.2"

androidx_core = "1.12.0"
appcompat = "1.6.1"
fragment-ktx = "1.6.1"
activity-ktx = "1.8.2"

activity-compose = "1.8.2"
androidx-lifecycle = "2.8.4"
compose-multiplatform = "1.7.0"

dataStore = "1.1.2"
mmkv = "1.3.0"
androidx_preference = "1.2.0"

m3ColorUtilities="1.0"
autoServiceKsp = "1.2.0"
autoService = "1.1.1"
#koin
koin-bom = "4.0.2"
koin-annotation = "2.0.0"
okio = "3.10.2"
[libraries]
#AndroidX核心库
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx_core" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "androidx_preference" }
github-mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "dataStore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }

github-knightwood-m3ColorUtilities = { module = "com.github.knightwood:MaterialColorUtilities", version.ref = "m3ColorUtilities" }

mavenPublish = { group = "com.vanniktech.maven.publish", name = "com.vanniktech.maven.publish.gradle.plugin", version = "0.34.0" }

autoService-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref = "autoServiceKsp" }
autoService-annoations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }

# koin -kotlin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines" }
# koin -android
koin-core-android = { module = "io.insert-koin:koin-android" }
#koin -compose -compose multiplatform
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation" }
# koin 注解。 android或是ktor中使用的
koin-annotations-bom = { module = "io.insert-koin:koin-annotations-bom", version.ref = "koin-annotation" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotation" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotation" }


[plugins]
# kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

# compose编译器
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
# kmp compose bom插件
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
# 多平台库发布插件
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
kotlins-android = ["kotlin-coroutines-core", "kotlin-coroutines-android"]
